#ifndef GRADER_H
#define GRADER_H
 
#include <stddef.h>
 
/* Filled in by run_libc() and run_mm() */
typedef struct {
    size_t peak_payload;   /* peak sum of live requested bytes        */
    size_t heap_size;      /* final heap size (mm only; 0 for libc)   */
    int    errors;         /* unexpected NULLs                        */
} TraceResult;
 
/* Generated by gen_trace – implemented in trace_ops.c */
void run_libc(TraceResult *r);
void run_mm(TraceResult *r);
int  trace_num_ops(void);
int  trace_num_ids(void);
 
#endif
 